/**
 * @file plugin:san/essential
 */

module.exports = {
    extends: require.resolve('./base'),
    rules: {
        'san/custom-event-name-casing': 'error',
        'san/no-arrow-functions-in-watch': 'error',
        'san/no-async-in-computed-properties': 'error',
        'san/no-custom-modifiers-on-v-model': 'error',
        'san/no-dupe-keys': 'error',
        'san/no-dupe-v-else-if': 'error',
        'san/no-duplicate-attributes': 'error',
        'san/no-multiple-template-root': 'error',
        'san/no-mutating-props': 'error',
        'san/no-parsing-error': 'error',
        'san/no-reserved-keys': 'error',
        'san/no-shared-component-data': 'error',
        'san/no-side-effects-in-computed-properties': 'error',
        'san/no-template-key': 'error',
        'san/no-textarea-mustache': 'error',
        'san/no-unused-components': 'error',
        'san/no-unused-vars': 'error',
        'san/no-use-v-if-with-v-for': 'error',
        'san/no-v-for-template-key': 'error',
        'san/no-v-model-argument': 'error',
        'san/require-component-is': 'error',
        'san/require-prop-type-constructor': 'error',
        'san/require-render-return': 'error',
        'san/require-v-for-key': 'error',
        'san/require-valid-default-prop': 'error',
        'san/return-in-computed-property': 'error',
        'san/use-v-on-exact': 'error',
        'san/valid-template-root': 'error',
        'san/valid-v-bind-sync': 'error',
        'san/valid-v-bind': 'error',
        'san/valid-v-cloak': 'error',
        'san/valid-v-else-if': 'error',
        'san/valid-v-else': 'error',
        'san/valid-v-for': 'error',
        'san/valid-v-html': 'error',
        'san/valid-v-if': 'error',
        'san/valid-v-model': 'error',
        'san/valid-v-on': 'error',
        'san/valid-v-once': 'error',
        'san/valid-v-pre': 'error',
        'san/valid-v-show': 'error',
        'san/valid-v-slot': 'error',
        'san/valid-v-text': 'error'
    }
};
